shorebirdtech/website

- src/pages/demo.html
Adds a demo.html page to make shorebird.dev/demo redirect to https://calendly.com/eseidel/shorebird-demo.
> chore: add redirecting demo.html

- src/components/FAQ.tsx
- src/config.ts
Fix a few more places mentioning our direct invite link instead of our "vanity url"
> chore: move to use our discord vanity url everywhere

- astro.config.mjs
Before we used Astro we had .html suffixes on all our routes,
now we don't, but some docs (including /terms itself) still points
to /terms.html.  I don't want to modify /terms.html itself so
I'm adding the redirect.  We can update the url in /terms
next time we modify the Terms.
> chore: redirect /terms.html to /terms

- src/pages/index.astro
**READY**
Tiny nit: This PR moves the "docs" button to the end of the navigation bar to be consistent in showing all buttons that just scroll to the section within the page first, and the buttons that exit the page.
Before this pull request:
* Home -> scrolls to section
* Products -> scrolls to section
* Pricing -> scrolls to section
* Team -> scrolls to section
* Newsletter -> scrolls to section
* Docs -> redirects to a new page
* FAQ -> scrolls to section
After this pull request:
* Home -> scrolls to section
* Products -> scrolls to section
* Pricing -> scrolls to section
* Team -> scrolls to section
* Newsletter -> scrolls to section
* FAQ -> scrolls to section
* Docs -> redirects to a new page
Please don't hesitate to close this PR if don't agree with it. Also I don't if there were …
> feat: move "docs" button to the end of the navigation

- src/components/Hero.tsx
- src/config.ts
- src/layouts/MainLayout.astro
**READY**
- feat: improve SEO (closes https://github.com/shorebirdtech/shorebird/issues/1223)
> feat: improve SEO

- astro.config.mjs
- package-lock.json
- package.json
- src/layouts/MainLayout.astro
Google search console suggested we do this?  No clue if it's a good idea or worth doing.
> chore: add sitemap

- src/components/FAQ.tsx
I also fixed the link to our project boards which was stale.
> doc: update our FAQ answers

- src/pages/terms/index.md
This replaces our previous 2023 TOS for all customers.
Our 2023 TOS were written by me (a non-lawyer), cribbed from what
expo.dev was using for their Terms at the time.  This set is
written by an actual lawyer, with the goals of:
1. Be as much like every other Saas.
2. Make it easy for companies to adopt Shorebird.
Terms are currently scheduled to go into affect on Feb 24, 2024
for new customers, and March 24, 2024 for existing customers.
All customers will be required to make an affirmative accept
before those dates to continue using the services.
**READY/IN DEVELOPMENT/HOLD**
> docs: Update Shorebird TOS for 2024

- Dockerfile
**READY**
npm ci (also known as clean-install) is most suited for building docker images for deployments and release, as it only install the packages and dependent packages from package-lock.json, where npm install fetches dependencies and dependent packages during that time from package.json and generates new package-lock.json and could update packages which introduce new unexpected behaviors. See more here [`npm ci`](https://docs.npmjs.com/cli/v9/commands/npm-ci)
It reduces significantly the installation time during building docker
`npm install` took `139s`  where
`npm ci` took `129s`
we got `10s` :)
> enhancement(build): Replacing npm install with npm ci as it quicker

- src/config.ts
Blog was overflowing and not showing up.  Removed some less-needed
links.
> fix: remove links from nav-bar

- src/pages/blogs/ios-beta.md
This was deleted a while ago before we had a blogs/ landing page.
Google Search Console warned us of incoming failed links.
> chore: restore iOS Beta blog post

- src/pages/privacy/index.md
Adding:
Cloudflare (used for patch delivery, CDN), no private customer
data is ever held here, but listing for full transparency.
Plausible for cookie-less, EU-compliant website analytics.
Sentry for website error reporting.
> docs: update our list of vendors

- src/components/PricingDetails.tsx
- src/components/PricingOverview.tsx
- src/config.ts
Use a new (30m) URL for sales calls and make it clear its speaking to sales more generally rather than implying a demo.
> chore: small updates to pricing page

- src/components/PricingFAQ.tsx
A customer asked, figured an FAQ answer was the correct way to answer.
> doc: add a section about when charged for patch installs

- src/components/Footer.tsx
- src/pages/contact.md
The page existed, we just weren't using it.
This came up because a contract needed our physical address and I realized it wasn't on our site.
> feat: Use /contact for our contact page

- cspell.config.yaml
- src/content/blog/shorebird-code-push-v2.md
- src/content/blog/tracks-percentage-rollouts-a-b-testing.md
This isn't quite accurate, since we've doing enums for now instead of strings.  We can just remove the A/B testing mentions and put them in a later blog post once we move to strings?  Or we could re-consider using strings now to support those.
> docs: take a first stab at an % rollouts blog

- src/components/PricingCalculator.tsx
- src/components/PricingDetails.tsx
- src/utils/formatters.tsx
Adds a pricing calculator to the pricing page:
https://github.com/user-attachments/assets/47e5f087-eb3c-4926-b47d-63f59d55f1e6
> feat: add calculator to pricing page

- astro.config.mjs
**READY**
Adding in a vanity URL for sending people to the newsletter signup form. Allows us to post a Shorebird URL for that flow instead of a weird MailChimp one.
> feat: add vanity url for newsletter signup

- src/content/success-stories/visible.md
**READY**
Pulling the app images out of the Visible success story as they were broken. Need to do more work to get them rendered correctly.
> fix: removing broken images from visible story

- astro.config.mjs
**READY**
Adding a `\talk-to-sales` vanity URL for use on socials. Also alphabetized the redirects list.
to change)
> feat: Add talk to sales url

- src/config.ts
- src/content/config.ts
- src/content/jobs/developer-relations-marketing-lead.md
- src/content/jobs/full-stack-software-engineer.md
- src/content/jobs/marketing-lead.md
- src/layouts/job.astro
- src/pages/jobs/[...slug].astro
- src/pages/jobs/index.astro
- src/pages/privacy/index.md
Migrates the /jobs page to a content collection, similar to /blog. Each job is now a separate file in src/content/jobs, and /jobs is a page that shows cards for each open job.
> feat: migrate jobs to content collection
