shorebirdtech/website

- astro.config.mjs
- public/CNAME
- src/components/Footer.tsx
**HOLD**
- chore: add CNAME (this should only be merged once the DNS settings are updated)
> chore: add CNAME

- src/components/FAQ.tsx
> fix: faq link

- package-lock.json
- package.json
- src/components/FAQ.tsx
- src/components/Hero.tsx
- src/components/Pricing.tsx
- src/config.ts
- src/pages/index.astro
**READY**
- feat: update FAQs and add enterprise tier
> feat: update FAQs and add enterprise tier

- Dockerfile
- docker-compose.yaml
**HOLD**
- fix: `docker compose up --build` (closes #12)
> fix: `docker compose up --build`

- .vscode/settings.json
- package-lock.json
- src/components/FAQ.tsx
- src/components/Footer.tsx
- src/components/Hero.tsx
- src/components/Navbar.tsx
- src/components/NewsLetter.tsx
- src/components/Pricing.tsx
- src/components/ProductsCodePush.tsx
- src/components/PromoVideo.tsx
- src/components/Team.tsx
- src/layouts/MainLayout.astro
- src/layouts/MarkdownLayout.astro
- src/pages/index.astro
- tsconfig.json
**READY**
- feat: various website updates (closes #17 closes #18)
> feat: various website updates

- src/components/ProductsCodePush.tsx
**READY**
- chore: remove asset support until it is available
> chore: remove asset support until it is available

- src/components/NewsLetter.tsx
**READY**
- fix: add motion transition to newsletter component
> fix: add motion transition to newsletter component

- src/assets/icons/CheckArrowIcon.tsx
- src/components/FAQ.tsx
- src/components/Hero.tsx
- src/components/Pricing.tsx
- src/components/ProductsCodePush.tsx
- src/components/PromoVideo.tsx
- src/components/Team.tsx
- src/pages/index.astro
- src/styles/Theme.css
- tailwind.config.cjs
**HOLD**
- feat: revamp pricing
> feat: revamp pricing

- src/components/FAQ.tsx
**READY**
- fix(faq): discord link
> fix(faq): discord link

- src/components/Pricing.tsx
- src/components/ProductsCodePush.tsx
- src/config.ts
**READY**
- feat: update getting started CTA
> feat: update getting started CTA

- src/components/Footer.tsx
- src/components/Navbar.tsx
**READY**
- feat: add sign in button
- feat: update footer to include links to console and documentation site
> feat: add sign in button

- src/components/Team.tsx
> fix: typo in team section

- src/pages/jobs.md
> fix: Remove Founding Compiler Engineer posting

- src/components/FAQ.tsx
- src/components/NewsLetter.tsx
- src/components/ProductsCodePush.tsx
iOS is now ready for public use!
> feat: move iOS to alpha status

- src/components/Team.tsx
**READY**
- style(team): adjust padding
> style(team): adjust padding

- src/pages/index.astro
> Add Documentation link to nav bar

- src/components/Navbar.tsx
**READY**
- feat: rename "Sign In" to "Console" in navbar
- this resolves the overflow that can occur if a user resizes their browser window to just above the mobile breakpoint
- it also is a bit more clear since the "Sign In" also functioned as a "Sign Up" button.
> feat: rename "Sign In" to "Console" in navbar

- package-lock.json
**READY**
- chore: `npm audit`
> chore: `npm audit`

- src/components/Pricing.tsx
- src/components/ProductsCodePush.tsx
- src/styles/Theme.css
**READY**
- feat(pricing): add Team Tiers
> feat(pricing): add Team Tiers

- src/components/Pricing.tsx
**READY**
- Adds dynamic community/private support level to team pricing tier depending on slider value
- Fixed tapping outside of tiers modal closes the modal
> feat: add dynamic support level to team tier

- astro.config.mjs
- src/pages/pricing.astro
**READY**
- feat: add `/pricing` which redirects to https://shorebird.dev#pricing
> feat: add `/pricing`

- .github/workflows/main.yaml
- package-lock.json
- package.json
- src/components/FAQ.tsx
- src/components/NewsLetter.tsx
- src/components/ProductsCodePush.tsx
- src/components/Team.tsx
**READY**
- chore(deps): upgrade to Astro 3.x
https://docs.astro.build/en/guides/upgrade-to/v3/
> chore(deps): upgrade to Astro 3.x

- src/pages/privacy/index.md
- src/pages/privacy/raw.ts
**READY**
- feat(privacy): add `privacy/raw` endpoint
> feat(privacy): add `privacy/raw` endpoint

- package-lock.json
- package.json
I was attmepting to resolve the astro/zod "low" npm audit warning
that GitHub is showing on every commit, but this didn't fix it.
Regardless, seemed worth commiting.  No clue how to run tests if any.
> chore: Run `npm upgrade`

- src/pages/privacy/index.md
- Slight wording changes in a few places from our new lawyers.
- Removed Digital Ocean and added Loops.so
> feat: Update Privacy Policy

- src/pages/jobs.md
**READY**
- fix minor typos in `jobs.md`
> chore(jobs): fix typos

- src/components/Pricing.tsx
This would need to be made pretty before landing, but is the general idea.
> docs: explain what "patch installs" means

- src/pages/jobs.md
The two most common confusions when applying to this job are:
1. not understanding it's about working on Flutter itself (e.g C++) rather than using Flutter.
2. out side of our considered timezones.
Attempting to clarify.
> fix: clarify location requirements

- src/components/Blogs.astro
- src/config.ts
**READY**
- style: improve blog styles
- chore: re-adds the product navbar header since it fits and seemed worth re-adding
> style: improve blog styles

- src/pages/blogs/1.0.md
- src/pages/blogs/how-shorebird-works.md
**READY**
- docs: adjust blog descriptions
> docs: adjust blog descriptions

- src/components/Blogs.astro
**READY**
- feat: sort blogs by date so that newer blogs appear first
> feat: sort blogs by date

- src/components/BlogSubscribe.tsx
- src/layouts/BlogLayout.astro
- src/pages/blogs/1.0.md
- src/pages/blogs/how-we-built-code-push.md
This was feedback from a reviewer.
Layout isn't great, but it's probably good enough for now.
> feat: add subscribe button at bottom of blog

- src/components/Blogs.astro
- src/components/Footer.tsx
**READY**
- fix: blog page footer position
> fix: blog page footer position

- src/components/FAQ.tsx
Thank you to Bryan for the suggestion.
> feat: add an FAQ about seeing source code.

- src/components/Customers.tsx
**READY**
Here are some of my suggestions for the logo design.
- Aligned logos and text
- Split into a title and subtitle
- Changed to 3 logs instead of 4, I think 4 were way too many (we could get the logos randomly on page build in the future?)
https://github.com/shorebirdtech/website/assets/835641/36cc9802-10dc-41e5-a0fd-3426bb3412dc
> feat: Logo design tweaks

- src/pages/blogs/patch-signing-beta.md
> docs: add an announcement of patch signing beta

- src/pages/blog/patch-signing-beta.md
I'm sure we can do a lot more cross-linking but figured this
was a start.
> chore: add a link to previous post

- astro.config.mjs
This matches /privacy and /terms
> chore: add redirect for /security

- src/components/StableBanner.tsx
- src/pages/index.astro
> chore: remove 1.0 blog announce banner

- src/components/FAQ.tsx
Looked a little cleaner this way?
I also updated the "what platforms" question slightly.
> chore: close FAQs by default

- .github/workflows/main.yaml
- package-lock.json
Site still seems to run w/o error.  We don't appear to have
any npm tests to confirm or deny, so tested manually.
> chore: run `npm update`

- package-lock.json
- package.json
**READY**
- chore(deps): `npx @astrojs/upgrade`
> chore(deps): `npx @astrojs/upgrade`

- src/components/Brands.tsx
- src/components/Testimonials.tsx
**READY**
- style: adjust brands and testimonial styles
> style: adjust brands and testimonial styles

- src/pages/jobs.md
**READY**
Changed benefits.md link to the new link provided by @eseidel in https://github.com/shorebirdtech/website/issues/131#issuecomment-2226485504
- [X ] 🛠️ Bug fix (non-breaking change which fixes an issue)
> [fix] stale benefits.md link

- src/components/FAQ.tsx
As per https://github.com/shorebirdtech/shorebird/issues/485.
> docs: Clarify we do not intend to support on-prem anytime soon.

- src/layouts/BlogLayout.astro
- src/layouts/MainLayout.astro
- src/layouts/MarkdownLayout.astro
Test-driving https://plausible.io/
> chore: set up plausible analytics

- .github/workflows/main.yaml
- package-lock.json
- package.json
- src/components/Brands.tsx
- src/pages/blog/ios-beta.md
- src/pages/contact.md
Also added a #brands link to the homepage and fixed the spelling
errors that cspell found.
> feat: add cspell to CI

- src/pages/blog/patch-rollback.md
**READY**
Adds a blog post announcing patch rollbacks
> Add patch rollback blog post

- src/components/Pricing.tsx
**IN DEVELOPMENT**
Updates the teams card for the pay-as-you-go plan
> feat: add pay-as-you-go plan card

- src/components/Blogs.astro
- src/components/Card.tsx
- src/pages/blog/1.0.md
- src/pages/blog/dart-3.5.0.md
- src/pages/blog/how-we-built-code-push.md
- src/pages/blog/ios-beta.md
- src/pages/blog/patch-rollback.md
- src/pages/blog/patch-signing-beta.md
- src/pages/blog/simplified-pricing.md
- src/pages/blog/viewing-logs.md
**READY**
- feat(blog): improve card styles and date parsing
> feat(blog): improve card styles and date parsing

- src/layouts/MainLayout.astro
**READY**
- fix: canonical link (improves our SEO)
> fix: canonical link

- package-lock.json
It had been at least 30s since we last did this.
> chore: run npm update

- src/components/Brands.tsx
- src/components/JobsBanner.tsx
- src/pages/index.astro
- src/pages/jobs.md
Hiring for two roles:
* Systems Engineer
* Go-to-market lead
> feat: add back our jobs page

- src/components/JobsBanner.tsx
**READY**
- fix: jobs banner z-index
> fix: jobs banner z-index

- src/components/BlogFooterPitch.tsx
- src/layouts/BlogLayout.astro
**READY**
Adds extra visual weight and a CTA to our blog footer.
Desktop:
Mobile:
> feat: make Shorebird blog footer louder

- src/pages/jobs.md
**READY**
- fix(jobs): broken link for engineering role
> fix(jobs): broken link for engineering role

- package-lock.json
**READY**
- chore(deps): `npm audit fix`
> chore(deps): `npm audit fix`

- src/pages/jobs.md
I still lack the correct vocabulary to describe this role, but hopefully this is a better fit than GTM lead was.
> docs: update the "founding product manager" description

- package-lock.json
- package.json
**READY**
- chore(deps): upgrade to astro 5
> chore(deps): upgrade to astro 5

- components.json
- package-lock.json
- package.json
- src/components/PricingCalculator.tsx
- src/components/ui/card.tsx
- src/components/ui/label.tsx
- src/components/ui/slider.tsx
- src/lib/utils.ts
- src/styles/Theme.css
- tailwind.config.cjs
**READY**
- feat(pricing): add patch cost calculator (closes https://github.com/shorebirdtech/website/issues/212)
> feat(pricing): add patch cost calculator

- src/components/Banner.tsx
- src/pages/index.astro
**READY**
- feat: update banner to link to workshop
> feat: update banner to link to workshop

- src/components/PricingDetails.tsx
- src/components/PricingOverview.tsx
- src/components/ProductsCodePush.tsx
- src/config.ts
**READY**
https://github.com/user-attachments/assets/c593bce5-9bd5-4e5d-bf80-776b8a57f72c
> feat: simplify pro plan signup

- src/components/PricingDetails.tsx
**READY**
- feat(pricing): rename custom to enterprise on /pricing
> feat(pricing): rename custom to enterprise on /pricing

- src/components/PricingDetails.tsx
- src/components/PricingOverview.tsx
- src/config.ts
**HOLD**
- feat: add new business tier
> feat: add new business tier

- src/content/blog/windows-beta.md
Add a blog post announcing windows beta.
> docs: announce windows beta

- src/components/FAQ.tsx
- src/components/ProductsCodePush.tsx
**READY**
- feat: include windows and macos support
> feat: include windows and macos support

- src/components/Banner.tsx
- src/components/ProductsCodePush.tsx
**READY/IN DEVELOPMENT/HOLD**
- chore: update banner to highlight windows beta
> chore: update banner to highlight windows beta

- src/layouts/BlogLayout.astro
https://www.linkedin.com/help/linkedin/answer/a521928
> fix: add missing og:title to hopefully make LinkedIn happy?

- src/config.ts
- src/pages/contact.md
**READY**
Updating the sales booking link so it points to the round robin for Tom and Eric
> feat: Update sales call booking link

- cspell.config.yaml
- src/content/blog/buy-dont-build.md
> feat: adding buy don't build blog post

- src/components/pricing-details.astro
- src/components/pricing-overview.astro
- src/components/pricing-plans.astro
**READY**
- refactor: create pricing plans component
> refactor: create pricing plans component

- src/pages/blog/index.astro
**READY**
- chore(blog): adjust heading style on mobile
> chore(blog): adjust heading style on mobile

- src/components/home/success-stories-overview.astro
- src/pages/success-stories/index.astro
**READY**
- fix: sort success stories by date
> fix: sort success stories by date

- src/content/success-stories/junglee-games.md
**READY**
Updating title for Bhavest per request
> fix: update title for quote in Junglee story

- package-lock.json
- src/layouts/blog.astro
- src/pages/blog/[...slug].astro
**READY**
- feat(blog): add dynamic reading time
> feat(blog): add dynamic reading time

- src/content/success-stories/pushpress.md
**READY**
Removing the extra space on the PushPress success story which their marketing team asked for. This also changes the URL as we went from `push-press` to `pushpress` but not super worried about that as we can update the social posts.
> fix: update pushpress name

- src/pages/jobs.md
We're not actively hiring at this time.
> chore: remove founding engineer post

- src/components/home/for-developers.astro
- src/components/ui/navbar.tsx
**READY**
- chore: update star count and number of users
to change)
> chore: update star count and number of users

- src/components/newsletter/newsletter-form.tsx
- src/components/ui/input.tsx
- src/pages/newsletter-signup.astro
**READY**
- feat: improve newsletter signup
to change)
> feat: improve newsletter signup

- src/pages/terms/index.md
**READY**
Updating the page title to match the document title. My OCD was twitching seeing the mismatch.
to change)
> fix: update title for ToS

- src/components/ui/navbar.tsx
**READY**
Simple update while I was in the repo
to change)
> feat: update github stars number

- package-lock.json
- package.json
**READY**
- chore(deps): upgrade astro
to change)
> chore(deps): upgrade astro

- src/components/ui/footer.astro
- src/config.ts
**READY**
- feat: link to compliance from ISO badge
to change)
> feat: link to compliance from ISO badge

- src/components/home/faq.astro
- src/components/home/features.astro
- src/components/home/for-developers.astro
- src/components/home/for-teams.astro
- src/components/home/problem.astro
- src/components/home/success-stories-overview.astro
- src/components/pricing/pricing-calculator.tsx
- src/components/pricing/pricing-plans.tsx
- src/components/scroll-to-top-button.tsx
- src/components/ui/sheet.tsx
- src/layouts/blog.astro
- src/layouts/success-story.astro
- src/pages/blog/index.astro
- src/pages/jobs/index.astro
- src/pages/success-stories/index.astro
**READY**
- refactor: various site cleanup
to change)
> refactor: various site cleanup

- src/content/jobs/mobile-runtime-software-engineer.md
**READY**
Fixing spelling issue so this will deploy
to change)
> fix: correct spelling issue

- src/config.ts
- src/content/jobs/marketing-lead.md
It's just too much volume to keep just in my inbox.
> fix: route hiring email to a list instead of my inbox directly

- src/pages/index.astro
**READY**
- feat: update banner to link to ci blog
to change)
> feat: update banner to link to ci blog

- src/content/success-stories/flame.mdx
- src/layouts/success-story.astro
> docs: Add project links to success stories in flame.mdx
